services: 
  app:
      build: .
      container_name: node_postgres
      environment:
       - DATABASE_URL=postgresql://curry0312:curry1357911@db:5432/mydb
       - JWT_SECRET=curry_jwt_secret
       - NODE_ENV=development
       - PORT=8383
      ports:
          - "8383:8383"
      # restart: always
      volumes:
        - .:/app
      depends_on:
        - db
  db:
    image: postgres:13-alpine
    container_name: node_postgres-db
    # restart: always
    environment:
      POSTGRES_USER: curry0312
      POSTGRES_PASSWORD: curry1357911
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  
     